### ISSUE TITLE
Invalid css error when importing foundation (even after updating sass-rails)

### ISSUE THREAD

**Issue by itsjms** [igorkasyanchuk/rails_db#11]
- On Rails 4.1.1
- On Ruby 2.1.1p76
- Using sass-rails 5.0.4
- Using foundation-rails 5.5.0.0
- Using sass 3.2.19

Still having the same: `Invalid CSS after "...ules: $modules ": expected "}", was "!global;"` occurring when visiting the page.

**Comment by igorkasyanchuk** [comment]
Works with

gem 'rails_db'
gem 'sass', '>= 3.3.14'
gem 'sass-rails', '>= 5.0.0'
gem 'foundation-rails', '5.5.0.0'

**Comment by rhuppert** [comment]
I am experiencing the same issue.
I'm still on Foundation 4.3.2 and have dependencies preventing updating sass-rails and moving from the zurb-foundation gem to foundation-rails.
I wonder if rails_db might would benefit by being an engine and possibly make this a non-issue?
Regardless, nice work!

**Comment by igorkasyanchuk** [comment]
I suggest you to create simple "hello world" app where I (or somebody) can reproduce issue, because it's difficult to understand what env you using and what other gems. Maybe you can create zip-file with source code and put in somewhere, or just repo in github? 

Probably I've a solution here, I think it might work.
If you (or somebody) can handle this it might be very cool - we can use plain JS/CSS files from Foundation, and just put them into app/assets. 

Probably also older version of foundation need to be used.

Another solution can be for you - extract content of rails_db gem to vendor/gems/rails_db', change gemfile, application.js/css, some "requires" and include it in your project as 
gem 'rails_db', path: 'vendor/gems/rails_db'

PS: looks like zurb-foundation gem is very old now, I really suggest to upgrade, I know it's painful, but better to do it now then later.

**Comment by igorkasyanchuk** [comment]
Issue is created https://github.com/igorkasyanchuk/rails_db/issues/21
@rhuppert can you handle it?
this is instructions how to do development locally https://github.com/igorkasyanchuk/rails_db#local-development
I can help if anything, my skype: igorkasyanchuk

**Comment by rhuppert** [comment]
Thanks for the information.  I’m off on holiday as of today, but will give it a shot upon my return to work.  

 

And you are correct, I have been putting off the Foundation update to avoid the pain.  Again, thanks for the insight.

**Comment by itsjms** [comment]
Ya making the assets css / js might be the best idea for people to be able to easily integrate this gem. I personally had to give up because we were having to update a bunch of our apps gems and it was causing problems. If we could get around this SASS issues with foundation I think we would be able to use it.

**Comment by igorkasyanchuk** [comment]
You can already use version of gem from "master", I think it should work.
Release planned to be made soon
